# Generated by Django 3.2.12 on 2022-03-29 18:40

import dice.apps.rounds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='value',
            field=models.PositiveSmallIntegerField(default=dice.apps.rounds.models.roll_dice),
        ),
    ]
