version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - docker.env

  web:
    build:
      context: .
      dockerfile: ./.devops/docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    depends_on:
      - db
    image: krysiaek/dice
