# Generated by Django 3.2.9 on 2022-01-09 12:28

import dice.apps.games.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='start_game',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='who_started_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('figure', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '3x'), (8, '4x'), (9, '3+2x'), (10, 'Small straight'), (11, 'Large straight'), (12, 'Yatzy'), (13, 'Chance')], null=True)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_points', models.PositiveIntegerField(default=0)),
                ('dice1', models.OneToOneField(default=dice.apps.games.models.Dice.create, on_delete=django.db.models.deletion.CASCADE, related_name='round_as_first_dice', to='games.dice')),
                ('dice2', models.OneToOneField(default=dice.apps.games.models.Dice.create, on_delete=django.db.models.deletion.CASCADE, related_name='round_as_second_dice', to='games.dice')),
                ('dice3', models.OneToOneField(default=dice.apps.games.models.Dice.create, on_delete=django.db.models.deletion.CASCADE, related_name='round_as_third_dice', to='games.dice')),
                ('dice4', models.OneToOneField(default=dice.apps.games.models.Dice.create, on_delete=django.db.models.deletion.CASCADE, related_name='round_as_fourth_dice', to='games.dice')),
                ('dice5', models.OneToOneField(default=dice.apps.games.models.Dice.create, on_delete=django.db.models.deletion.CASCADE, related_name='round_as_fifth_dice', to='games.dice')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.room'),
        ),
    ]
