# Generated by Django 3.2.6 on 2021-09-07 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_room_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('chosen', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('figure', models.CharField(blank=True, max_length=15, null=True)),
                ('dice1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_as_first_dice', to='games.dice')),
                ('dice2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_as_second_dice', to='games.dice')),
                ('dice3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_as_third_dice', to='games.dice')),
                ('dice4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_as_fourth_dice', to='games.dice')),
                ('dice5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_as_fifth_dice', to='games.dice')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.room')),
            ],
        ),
    ]
