# Generated by Django 3.2.6 on 2021-09-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_dice_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
