# Generated by Django 3.2.12 on 2022-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20220225_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
