# Generated by Django 3.2.6 on 2021-09-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='figure',
        ),
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='room',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.room'),
            preserve_default=False,
        ),
    ]
