# Generated by Django 3.2.6 on 2021-09-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210914_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='figure',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '3x'), (8, '4x'), (25, '3+2x'), (30, 'Small straight'), (40, 'Large straight'), (50, 'Yatzy'), (100, 'Chance')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
