# Generated by Django 3.2.6 on 2021-10-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20211012_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
