# Generated by Django 3.2.6 on 2021-11-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_round_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dice',
            name='chosen',
        ),
    ]
