---
name: CI
on:
  push:
  workflow_dispatch:

jobs:
   tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: build docker-compose services
        run: docker-compose build
      - name: test
        run: |
          docker-compose run \
            -e DJANGO_SECRET_KEY="test" \
            -e TEST_OUTPUT_FILE_NAME="junit.xml" \
            -v "${{ github.workspace }}:/code" \
            --entrypoint "python manage.py test dice" \
            web
      - name: publish unit test report
        uses: EnricoMi/publish-unit-test-result-action@v1.31
        if: always()
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          files: junit.xml
          comment_mode: update last
          check_name: unit test report
          report_individual_runs: true
